# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java Credit Conveyor CI with Maven

on:
# ручной запуск по кнопке
  workflow_dispatch:
# запуск при пуше и ПР в указанные ветки
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    # воркфлоу запускать на этой ОС
    runs-on: ubuntu-latest

    steps:
    # репо копируется
    - name: 1. Check repo
      uses: actions/checkout@v3

    # This step uses the actions/setup-java action to configure
    # the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium
    - name: 2. Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: 3.1 Build ms with Maven
      run: mvn -B package --file ./pom.xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
#        verbose: true

